apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: codecrafterx/auth
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m" 
            limits:
              memory: "256Mi"
              cpu: "500m" 
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: auth-mongo-secret
                  key: MONGO_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET                  
          ports:
            - containerPort: 3000
