apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  type: NodePort
  selector:
    app: manager
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31141
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
        - name: manager
          image: codecrafterx/manager
          env:
            - name: VITE_API_URL
              value: http://auth:3000
          ports:
            - containerPort: 80
